import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import LoaderProvider from '@/components/context/LoaderContext';
import { TableProvider } from '@/components/context/TableContext';
import { AuthProvider } from '@/components/context/AuthContext';
import { ThemeProvider } from '@/components/context/ThemeContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Obstetra UI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} font-inter dark:bg-ob-black-11 dark:text-ob-white text-ob-black-4 bg-ob-white-2 antialiased`}
      >
        <ThemeProvider>
          <TableProvider>
            <LoaderProvider>
              <AuthProvider>{children}</AuthProvider>
            </LoaderProvider>
          </TableProvider>
        </ThemeProvider>

        <Toaster position="top-right" />
      </body>
    </html>
  );
}
